#!/bin/bash

rm -rf ./dist

mkdir -p dist/src
mkdir -p dist/bin
mkdir -p dist/res/sound

cp -r res dist
cp -r src dist

cp run.bat dist

cp /mnt/w/dev/canvas/Canvas/Release/Luau.exe dist/bin
cp /mnt/w/dev/canvas/Canvas/Release/*.dll dist/bin
cp /mnt/w/dev/canvas/Lua-5.4/lua54.dll dist/bin

rm -f ./dist/res/high_score
